### ISSUE TITLE
四个问题

### ISSUE THREAD

**Issue by shangchengwen** [google/pica#26]
1.初始化device是不是少了一个mac地址赋值

console.py
def pica_init_uci_device(
     self,
     mac_address: str = "00:00",

2.两个名字是不是要匹配?

web.rs
DeviceUpdated { .. } => "device-updated",

index.html
events.addEventListener("position-updated", (event) => {

3.项目目前是不是不完整，测距虽然开始了，但是没有测量的数据。

4.这个项目会持续做下去吗？

**Comment by SilverBzH** [comment]
Hi ! 

Thanks for opening an issue, could you please write down the issue in English ? It'll be better for everyone to understand ( I can't read chinese as well).

I'll use Google translate to understand your questions and hopefully the traduction is correct :). 

1. Yes indeed !
 
2. Nice catch :), yes they should. If you are interested you can open a PR directly to fix this. We should follow the "specification" in [openapi.yaml](https://github.com/google/pica/blob/main/static/openapi.yaml). Which mean the html is out of date and need to be updated, the rust part is right.

3. Yes the project is incomplete, there is some part of the specification which are missing such as the fragmentation for example and I believe some others. The plan here is to pass the test internally to have a first stable version, we'll see by then if we will tag it `v1.0.0` or not.

4. Yes. The pace of this project will be consistent but it is a 20% project. But we are currently working on it and we will support it as well. Thus said, there is still no external documentation available but it is in our bucket list.

Let me know if you'll open the PR to fix the two issues you found otherwise I'll do it.

谢谢你

**Comment by shangchengwen** [comment]
Thank you for your answers

Google translate is better than my English :)
